### ISSUE TITLE
Loki push API: Add `can_connect` guard in relation events.

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/loki-k8s-operator#128]
### Bug Description

Sometimes `_on_logging_relation_changed` is fired before `pebble_ready`.

For instance two methods "inside" `_on_logging_relation_changed` we are executing:

```python
        files = container.list_files(self._rules_dir)
``` 
And if Pebble is not ready, and `ops.pebble.ConnectionError` is raise

### To Reproduce

See: https://github.com/canonical/grafana-agent-k8s-operator/runs/5771963079?check_suite_focus=true#step:4:530

### Environment

All versions of loki_push_api lib

### Relevant log output

```shell
Traceback (most recent call last):
  File "./src/charm.py", line 242, in <module>
    main(LokiOperatorCharm)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 283, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 743, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 790, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1237, in _on_logging_relation_changed
    self._process_logging_relation_changed(event.relation)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1263, in _process_logging_relation_changed
    self._remove_alert_rules_files(self.container)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1361, in _remove_alert_rules_files
    files = container.list_files(self._rules_dir)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1301, in list_files
    return self._pebble.list_files(path, pattern=pattern, itself=itself)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1807, in list_files
    resp = self._request('GET', '/v1/files', query)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1281, in _request
    response = self._request_raw(method, path, query, headers, data)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1328, in _request_raw
    raise ConnectionError(e.reason)
ops.pebble.ConnectionError: [Errno 2] No such file or directory
```

**Comment by balbirthomas** [comment]
Closed PR https://github.com/canonical/loki-k8s-operator/pull/132 since fix is moved to #152 .
