### ISSUE TITLE
Setting alertmanager's external url to a url without a port number breaks loki

### ISSUE THREAD

**Issue by sed-i** [canonical/loki-k8s-operator#217]
### Bug Description

In the absence of a port number, loki charm code sets the port to "None" and attempts to restart the new pebble command, which immediately exits.

### To Reproduce

1. `juju deploy --channel=edge cos-lite --trust`
2. `juju config alertmanager web_external_url=http://unre.al`

### Environment

```
Model  Controller  Cloud/Region        Version  SLA          Timestamp
m4     chdv2934    microk8s/localhost  2.9.34   unsupported  16:59:23-05:00

App           Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.23.0   active       1  alertmanager-k8s  edge      36  10.152.183.171  no       
catalogue              active       1  catalogue-k8s     edge       4  10.152.183.211  no       
grafana       9.2.1    active       1  grafana-k8s       edge      53  10.152.183.162  no       
loki          2.4.1    waiting      1  loki-k8s          edge      47  10.152.183.158  no       waiting for units to settle down
prometheus    2.33.5   active       1  prometheus-k8s    edge      83  10.152.183.75   no       
traefik                active       1  traefik-k8s       edge      93  192.168.1.10    no       
```

### Relevant log output

```shell
unit-loki-0: 16:54:28.838 DEBUG unit.loki/0.juju-log alertmanager:11: This unit's ingress URL: http://192.168.1.10:80/m4-loki-0
unit-loki-0: 16:54:28.910 INFO unit.loki/0.juju-log alertmanager:11: Pushed new configuration
unit-loki-0: 16:54:29.021 ERROR unit.loki/0.juju-log alertmanager:11: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 500, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 438, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 150, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py", line 171, in _on_relation_changed
    self.on.cluster_changed.emit()
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 856, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 157, in _on_alertmanager_change
    self._configure()
  File "./src/charm.py", line 269, in _configure
    self._container.restart(self._name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 1456, in restart
    self._pebble.restart_services(service_names)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1699, in restart_services
    return self._services_action('restart', services, timeout, delay)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/pebble.py", line 1721, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "loki" (cannot start service: exited quickly with code 1)
----- Logs from task 0 -----
2022-11-21T21:54:28Z INFO Service "loki" has never been started.
----- Logs from task 1 -----
2022-11-21T21:54:29Z INFO Most recent service output:
    (...)
    2022-11-21 21:54:28.988522 I | proto: duplicate proto type registered: grpc.DeleteIndexRequest
    2022-11-21 21:54:28.988524 I | proto: duplicate proto type registered: grpc.QueryIndexResponse
    2022-11-21 21:54:28.988564 I | proto: duplicate proto type registered: grpc.Row
    2022-11-21 21:54:28.988568 I | proto: duplicate proto type registered: grpc.IndexEntry
    2022-11-21 21:54:28.988569 I | proto: duplicate proto type registered: grpc.QueryIndexRequest
    2022-11-21 21:54:28.988571 I | proto: duplicate proto type registered: grpc.UpdateTableRequest
    2022-11-21 21:54:28.988612 I | proto: duplicate proto type registered: grpc.DescribeTableResponse
    2022-11-21 21:54:28.988621 I | proto: duplicate proto type registered: grpc.CreateTableRequest
    2022-11-21 21:54:28.988623 I | proto: duplicate proto type registered: grpc.TableDesc
    2022-11-21 21:54:28.988625 I | proto: duplicate proto type registered: grpc.TableDesc.TagsEntry
    2022-11-21 21:54:28.988663 I | proto: duplicate proto type registered: grpc.ListTablesResponse
    2022-11-21 21:54:28.988666 I | proto: duplicate proto type registered: grpc.Labels
    2022-11-21 21:54:28.988743 I | proto: duplicate proto type registered: storage.Entry
    2022-11-21 21:54:28.988747 I | proto: duplicate proto type registered: storage.ReadBatch
    level=info ts=2022-11-21T21:54:28.993462458Z caller=main.go:94 msg="Starting Loki" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
    level=info ts=2022-11-21T21:54:28.993827853Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
    level=info ts=2022-11-21T21:54:28.995012837Z caller=modules.go:682 msg="Not using boltdb-shipper index, not starting compactor"
    level=warn ts=2022-11-21T21:54:28.995184701Z caller=experimental.go:19 msg="experimental feature in use" feature="In-memory (FIFO) cache"
    level=info ts=2022-11-21T21:54:28.996097165Z caller=worker.go:109 msg="Starting querier worker using query-scheduler and scheduler ring for addresses"
    level=error ts=2022-11-21T21:54:28.996871624Z caller=log.go:106 msg="error running loki" err="parse \"http://unre.al:None\": invalid port \":None\" after host\nerror initialising module: ruler\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
2022-11-21T21:54:29Z ERROR cannot start service: exited quickly with code 1
-----
unit-loki-0: 16:54:29.253 ERROR juju.worker.uniter.operation hook "alertmanager-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by sed-i** [comment]
@Abuelodelanada this is an alertmanager bug but I wonder if we should catch the ChangeError and block.

**Comment by Abuelodelanada** [comment]
> @Abuelodelanada this is an alertmanager bug but I wonder if we should catch the ChangeError and block.


We are generating alertmanager config with this method:

```python
    def _alerting_config(self) -> str:
        """Construct Loki altering configuration.

        Returns:
            a string consisting of comma-separated list of Alertmanager URLs
            to send notifications to.
        """
        alerting_config = ""
        alertmanagers = self.alertmanager_consumer.get_cluster_info()

        if not alertmanagers:
            logger.debug("No alertmanagers available")
            return alerting_config

        return ",".join([f"http://{am}" for am in alertmanagers])
```

We are relying in what `get_cluster_info()` returns.... If I understand correctly, you are saying to validate the port here?

**Comment by sed-i** [comment]
I was thinking of maybe adding `try ... except ChangeError` around
```
  File "./src/charm.py", line 269, in _configure
    self._container.restart(self._name)
```
:point_up_2: that's where the traceback in the log was generated, from the pov of charm code.

**Comment by sed-i** [comment]
- Catching ChangeError and setting BlockState is debateable.
- The alertmanager issue was fixed.

Closing.
