### ISSUE TITLE
loki-k8s can't be related with 7 aplications. TooManyRelatedAppsError: Too many remote applications on logging

### ISSUE THREAD

**Issue by taurus-forever** [canonical/loki-k8s-operator#281]
### Bug Description

Hi,

We are checking COS implementation on DPE charm using this simple multipass blueprint: https://pastebin.canonical.com/p/HhZsjnw9dv/

Unfortunately `loki-k8s` got an error state after relating 7+ applications (it looks like this is constantly reproducible).

### To Reproduce

0. curl -o DB_COS.yaml https://pastebin.canonical.com/p/HhZsjnw9dv/plain/
1. multipass launch --name DB-COS --cloud-init DB_COS.yaml --memory 32G --cpus 12 --disk 100G --timeout 100500 # ETA: 1 hour to bootstrap
2. multipass delete DB-COS --purge # to clean test env

This will launch 2 controllers (lxd + microk8s) with the following models: "cos-k8s + mysql(-k8s) + postgresql(-k8s) + mongodb(-k8s)" and relate all of them together to send all metrics and logs into cos-lite.

### Environment

```
juju             2.9.42         22345  2.9/stable          canonical✓  classic
lxd              5.0.2-838e1b2  24322  5.0/stable/…        canonical✓  -
microk8s         v1.26.5        5352   1.26-strict/stable  canonical✓  -
```

### Relevant log output

```shell
unit-loki-0: 09:43:00 INFO unit.loki/0.juju-log ingress:4: reqs=ResourceRequirements(claims=None, limits={}, requests={'cpu': '0.25', 'memory': '200Mi'}), templated=ResourceRequirements(claims=None, limits=None, requests={'cpu': '250m', 'memory': '200Mi'}), actual=ResourceRequirements(claims=None, limits=None, requests={'cpu': '250m', 'memory': '200Mi'})
unit-loki-0: 09:43:00 ERROR unit.loki/0.juju-log ingress:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 529, in <module>
    main(LokiOperatorCharm, use_juju_for_storage=True)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/traefik_k8s/v1/ingress_per_unit.py", line 729, in _handle_relation
    self.on.revoked_for_unit.emit(self.relation)  # type: ignore
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 165, in _on_ingress_changed
    self.loki_provider.update_endpoint(url=self._external_url)
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/loki_k8s/v0/loki_push_api.py", line 1245, in update_endpoint
    if not self._charm.model.get_relation(self._relation_name):
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 249, in get_relation
    return self.relations._get_unique(relation_name, relation_id)
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/model.py", line 712, in _get_unique
    raise TooManyRelatedAppsError(relation_name, num_related, 1)
ops.model.TooManyRelatedAppsError: Too many remote applications on logging (6 > 1)
unit-loki-0: 09:43:00 ERROR juju.worker.uniter.operation hook "ingress-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

COS components revisions:
```
ubuntu@DB-COS:~$ juju status
Model    Controller  Cloud/Region        Version  SLA          Timestamp
cos-k8s  microk8s    microk8s/localhost  2.9.42   unsupported  09:45:54+02:00

App           Version  Status   Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.23.0   active       1  alertmanager-k8s  stable    47  10.152.183.108  no       
catalogue              active       1  catalogue-k8s     stable    13  10.152.183.175  no       
grafana       9.2.1    active       1  grafana-k8s       stable    64  10.152.183.223  no       
loki          2.4.1    waiting      1  loki-k8s          stable    60  10.152.183.73   no       waiting for units to settle down
prometheus    2.33.5   active       1  prometheus-k8s    stable   103  10.152.183.71   no       
traefik       2.9.6    waiting      1  traefik-k8s       stable   110  10.152.183.156  no       installing agent

Unit             Workload  Agent  Address     Ports  Message
alertmanager/0*  active    idle   10.1.96.87         
catalogue/0*     active    idle   10.1.96.77         
grafana/0*       active    idle   10.1.96.97         
loki/0*          error     idle   10.1.96.88         hook failed: "ingress-relation-changed"
prometheus/0*    active    idle   10.1.96.89         
traefik/0*       waiting   idle   10.1.96.86         gateway address unavailable

Offer                            Application  Charm           Rev  Connected  Endpoint              Interface                Role
grafana-dashboards               grafana      grafana-k8s     64   7/7        grafana-dashboard     grafana_dashboard        requirer
loki-logging                     loki         loki-k8s        60   6/7        logging               loki_push_api            provider
prometheus-metrics-endpoint      prometheus   prometheus-k8s  103  3/3        metrics-endpoint      prometheus_scrape        requirer
prometheus-receive-remote-write  prometheus   prometheus-k8s  103  4/4        receive-remote-write  prometheus_remote_write  provider
```

Note: 6 models used, but the model `postgresql-k8s` has two applications reported to cos-lite (`postgresql` and `pgbouncer`) => `7/7` connection to cos-lite.

P.S. this is similar to https://github.com/canonical/loki-k8s-operator/issues/256

**Comment by taurus-forever** [comment]
The issue is not reproducible on the channel `1.0/edge`:
```
App           Version  Status  Scale  Charm             Channel   Rev  Address         Exposed  Message
alertmanager  0.25.0   active      1  alertmanager-k8s  1.0/edge   77  10.152.183.56   no       
catalogue              active      1  catalogue-k8s     1.0/edge   13  10.152.183.160  no       
grafana       9.2.1    active      1  grafana-k8s       1.0/edge   82  10.152.183.127  no       
loki          2.7.4    active      1  loki-k8s          1.0/edge   91  10.152.183.70   no       
prometheus    2.43.0   active      1  prometheus-k8s    1.0/edge  129  10.152.183.209  no       
traefik       2.9.6    active      1  traefik-k8s       1.0/edge  129  10.76.203.155   no  

...

Offer                            Application  Charm           Rev  Connected  Endpoint              Interface                Role
grafana-dashboards               grafana      grafana-k8s     82   8/8        grafana-dashboard     grafana_dashboard        requirer
loki-logging                     loki         loki-k8s        91   8/8        logging               loki_push_api            provider
prometheus-metrics-endpoint      prometheus   prometheus-k8s  129  4/4        metrics-endpoint      prometheus_scrape        requirer
prometheus-receive-remote-write  prometheus   prometheus-k8s  129  4/4        receive-remote-write  prometheus_remote_write  provider

```

re: `grafana-agent-k8s`/`loki` - this is a new information for us. Can you please review: 
https://charmhub.io/mysql-k8s/docs/h-enable-monitoring
https://charmhub.io/mysql/docs/h-enable-monitoring
https://charmhub.io/postgresql/docs/h-enable-monitoring
https://charmhub.io/postgresql-k8s/docs/h-enable-monitoring
Maybe we need to adopt more things there?

Free free to close the issue. Tnx!

**Comment by simskij** [comment]
Added some suggestions [here](https://discourse.charmhub.io/t/charmed-mysql-k8s-how-to-enable-monitoring/9981/2?u=0x12b). These suggestions go for both k8s charms. Machine docs already look correct. GJ!
