### ISSUE TITLE
Loki-k8s integration with tempo-k8s errors out

### ISSUE THREAD

**Issue by shayancanonical** [canonical/loki-k8s-operator#436]
### Bug Description

Integrating loki-k8s with tempo-k8s (both from edge channels) results in an error on loki-k8s (see trace below). Since loki-k8s is in `error` state, the below trace is repeated`

### To Reproduce

1. juju deploy cos-lite --trust --channel edge
2. juju deploy tempo-k8s --channel edge
3. jhack imatrix fill

### Environment

juju: 3.4.3
microk8s: MicroK8s v1.27.13 revision 6744
ubuntu: 22.04.3 LTS

### Relevant log output

```shell
unit-loki-0: 14:21:17 ERROR unit.loki/0.juju-log tracing:36: Uncaught exception while in charm code:                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                 
  File "./src/charm.py", line 818, in <module>                                                                                                                                                                     
    main(LokiOperatorCharm)                                                                                                                                                                                        
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 549, in main                                                                                                                                
    manager = _Manager(charm_class, use_juju_for_storage=use_juju_for_storage)                                                                                                                                     
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 432, in __init__                                                                                                                            
    self.charm = self._make_charm(self.framework, self.dispatcher)                                                                                                                                                 
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 435, in _make_charm                                                                                                                         
    charm = self._charm_class(framework)                                                                                                                                                                           
  File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 342, in wrap_init                                                                                                   
    _tracer = get_tracer(_service_name)  # type: ignore                                                                                                                                                            
  File "/var/lib/juju/agents/unit-loki-0/charm/venv/opentelemetry/trace/__init__.py", line 515, in get_tracer                                                                                                      
    return tracer_provider.get_tracer(                                                                                                                                                                             
TypeError: get_tracer() takes from 2 to 4 positional arguments but 5 were given
```

**Comment by PietroPasotti** [comment]
just hit the same issue. Might be some version incompatibility with the otlp sdk

**Comment by PietroPasotti** [comment]
TODO: ssh into loki and see what otlp library is present. should be `opentelemetry-exporter-otlp-proto-http==1.21.0`
if it isn't, charmcraft is being nasty.

**Comment by PietroPasotti** [comment]
this is the version loki has:
![image](https://github.com/user-attachments/assets/659dc5fb-1624-499e-97fe-b6deead92dc3)

this is the version tempo has:
![image](https://github.com/user-attachments/assets/a0c467f4-7b33-447f-827b-1525ad2fee12)

while both are pinned to the same version. Something is funny

**Comment by PietroPasotti** [comment]
apparently loki ships with opentelemetry_api-1.26.0 which is incompatible with opentelemetry_sdk-1.21.0 instead of using 1.21.0 as well.

Probably something weird with charmcraft. Solution for now is probably to pin the transitive dependency as well.

**Comment by PietroPasotti** [comment]
How could this happen? 

- we didn't pin transitive dependencies
- probably different versions of charmcraft were used to pack the charms, resulting in only one being broken and the other one being fine
